### ISSUE TITLE
error when i use validate.py

### ISSUE THREAD

**Issue by szupzp** [meetshah1995/pytorch-semseg#69]
i want to validate my trained model but i got this error:
Traceback (most recent call last):
  File "validate.py", line 75, in <module>
    validate(args)
  File "validate.py", line 37, in validate
    state = convert_state_dict(torch.load(args.model_path)['model_state'])
  File "/media/sdc/zhanpeng/PycharmProjects/pytorch-semseg/ptsemseg/utils.py", line 58, in convert_state_dict
    for k, v in state_dict.items():
RuntimeError: OrderedDict mutated during iteration

so someone can help me to figure out?

**Comment by iacolippo** [comment]
This issue can be closed.

@szupzp it should be fixed now.

**Comment by szupzp** [comment]
@iacolippo Thank you!I will test the code right now!!!

**Comment by szupzp** [comment]
@iacolippo  it still have the same error when i validate the model!!
